
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    restart: always
    networks:
      - ok_network


networks:
  ok_network:
    external: true
