services:
  frontend:
    container_name: ok-service-frontend-${CONFIG_NAME}
    image: ${DOCKERHUB_USERNAME}/ok-service-frontend:${TAG}
    ports:
      - "${PORT}:80"  
    restart: always
    networks:
      - ok_network


networks:
  ok_network:
    external: true
